apiVersion: v1
kind: Service
metadata:
  namespace: memobase
  name: media-indexer-helper-service
  labels:
    app: media-indexer-helper-app
spec:
  ports:
    - port: 8083
  selector:
    app: media-indexer-helper-app
    tier: web
  clusterIP: None
